from django.conf import settings
from django.urls import include, path, re_path

from . import views

app_name = 'restrito'
urlpatterns = [
    path('', views.index, name='index'),
    path('compet_cartoes_senhas', views.compet_cartoes_senhas, name='compet_cartoes_senhas'),
    path('compet_feminina_cartoes_senhas', views.compet_feminina_cartoes_senhas, name='compet_feminina_cartoes_senhas'),
    path('compet_feminina_cartoes_senhas_cms', views.compet_feminina_cartoes_senhas_cms, name='compet_feminina_cartoes_senhas_cms'),
    path('compet_cartoes_senhas_cms', views.compet_cartoes_senhas_cms, name='compet_cartoes_senhas_cms'),
    path('compet_cartoes_senhas_cms_prev', views.compet_cartoes_senhas_cms_prev, name='compet_cartoes_senhas_cms_prev'),
    path('compet_recupera_cadastro', views.compet_recupera_cadastro, name='compet_recupera_cadastro'),
    path('compet_feminina_recupera_cadastro', views.compet_feminina_recupera_cadastro, name='compet_feminina_recupera_cadastro'),
    path('compet_recupera_elegivel_inscricao_cfobi', views.compet_recupera_elegivel_inscricao_cfobi, name='compet_recupera_elegivel_inscricao_cfobi'),
    path('compet_atualiza_senhas_lote', views.compet_atualiza_senhas_lote, name='compet_atualiza_senhas_lote'),
    path('compet_inscreve', views.compet_inscreve, name='compet_inscreve'),
    path('compet_feminina_inscreve/', views.compet_feminina_inscreve, name='compet_feminina_inscreve'),
    path('compet_feminina_inscreve_prog', views.compet_feminina_inscreve_prog, name='compet_feminina_inscreve_prog'),
    path('compet_feminina_inscreve_selecionadas_prog', views.compet_feminina_inscreve_selecionadas_prog, name='compet_feminina_inscreve_selecionadas_prog'),
    path('compet_feminina_inscreve_ini', views.compet_feminina_inscreve_ini, name='compet_feminina_inscreve_ini'),
    path('compet_feminina_inscreve_selecionadas_ini', views.compet_feminina_inscreve_selecionadas_ini, name='compet_feminina_inscreve_selecionadas_ini'),
    path('compet_feminina_inscreve_nova', views.compet_feminina_inscreve_nova, name='compet_feminina_inscreve_nova'),
    path('compet_inscreve_lote', views.compet_inscreve_lote, name='compet_inscreve_lote'),
    path('compet_feminina_inscreve_lote', views.compet_feminina_inscreve_lote, name='compet_feminina_inscreve_lote'),
    path('compet_inscreve_lote_senha', views.compet_inscreve_lote_senha, name='compet_inscreve_lote_senha'),
    path('compet_lista', views.compet_lista, name='compet_lista'),
    path('compet_feminina_lista', views.compet_feminina_lista, name='compet_feminina_lista'),
    path('compet_lista_rank/<str:compet_level>/', views.compet_lista_rank, name='compet_lista_rank'),
    path('compet_pre_inscricao_lista', views.compet_pre_inscricao_lista, name='compet_pre_inscricao_lista'),
    path('compet_feminina_pre_inscricao_lista', views.compet_pre_inscricao_lista, name='compet_feminina_pre_inscricao_lista'),
    path('compet_edita/<int:compet_id>', views.compet_edita, name='compet_edita'),
    path('compet_feminina_edita/<int:compet_id>', views.compet_feminina_edita, name='compet_feminina_edita'),
    path('compet_deleta/<int:compet_id>', views.compet_deleta, name='compet_deleta'),
    path('compet_deleta_lote', views.compet_deleta_lote, name='compet_deleta_lote'),
    path('compet_feminina_deleta_lote', views.compet_feminina_deleta_lote, name='compet_feminina_deleta_lote'),
    path('compet_valida/<int:id>', views.compet_valida, name='compet_valida'),
    path('certificados/<str:ctype>', views.emite_certificados_escola, name='emite_certificados_escola'),
    path('certificados_cf/<str:ctype>', views.emite_certificados_escola_cf, name='emite_certificados_escola_cf'),
    path('colab_inscreve', views.colab_inscreve, name='colab_inscreve'),
    path('colab_lista', views.colab_lista, name='colab_lista'),
    path('colab_edita/<int:colab_id>', views.colab_edita, name='colab_edita'),
    path('colab_deleta/<int:colab_id>', views.colab_deleta, name='colab_deleta'),
    path('colab_deleta_lote', views.colab_deleta_lote, name='colab_deleta_lote'),
    path('escola_edita', views.escola_edita, name='escola_edita'),
    path('coord_edita', views.coord_edita, name='coord_edita'),
    path('compet_lista_aut_prova_online/<str:exam_descr>/<str:turn>/', views.compet_lista_aut_prova_online, name='compet_lista_aut_prova_online'),
    path('compet_lista_status_prova_online/<str:exam_descr>/<str:turn>/', views.compet_lista_status_prova_online, name='compet_lista_status_prova_online'),
    path('compet_aut_prova_online/<str:exam_descr>/<str:turn>/', views.compet_aut_prova_online, name='compet_aut_prova_online'),
    path('compet_lista_classif_final/<str:level>', views.compet_lista_classif_final, name='compet_lista_classif_final'),
    path('compet_lista_classif_final_cf/<str:level>', views.compet_lista_classif_final_cf, name='compet_lista_classif_final_cf'),
    path('status_semana', views.partic_lista_status_semana, name='partic_lista_status_semana'),
    path('consulta_sede_fase3/<str:hash>/<int:reply_type>', views.consulta_sede_fase3, name='consulta_sede_fase3'),

    path('lista_desclassif', views.compet_lista_desclassif, name='compet_lista_desclassif'),
    path('relatorio_desclassif', views.compet_relatorio_desclassif, name='compet_relatorio_desclassif'),

]
