"""
Django settings for obi2026 project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from django.contrib.messages import constants as messages

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

YEAR = 2026

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-secure-pwnfcew3m$1*gpdqr7mg5ky#+m$vt0prwf6x1%i=q&k@!)%euf'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'olimpiada.ic.unicamp.br',
    'pj.provas.ic.unicamp.br',
    'p1.provas.ic.unicamp.br',
    'p2.provas.ic.unicamp.br',
    'ps.provas.ic.unicamp.br',
    '143.106.73.47',
    '143.106.73.36',
    '0.0.0.0',
    '127.0.0.1',
    'localhost',
]

CSRF_TRUSTED_ORIGINS = [
    'https://olimpiada.ic.unicamp.br',
    'https://pj.provas.ic.unicamp.br',
    'https://p1.provas.ic.unicamp.br',
    'https://p2.provas.ic.unicamp.br',
    'https://ps.provas.ic.unicamp.br',
]

# to allow iframes 
X_FRAME_OPTIONS = "SAMEORIGIN"

# Application definition

ASGI_APPLICATION = "obi2026.asgi.application"

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.flatpages',
    'principal.apps.PrincipalConfig',
    'faq.apps.FaqConfig',
    'fase1.apps.Fase1Config',
    'fase2.apps.Fase2Config',
    'fase2b.apps.Fase2bConfig',
    'fase3.apps.Fase3Config',
    'exams.apps.ExamsConfig',
    'cms.apps.CmsConfig',
    'restrito.apps.RestritoConfig',
    'cfobi.apps.CfObiConfig',
    'cal.apps.CalConfig',
    'compet.apps.CompetConfig',
    'blog.apps.BlogConfig',
    'blog_restrito.apps.BlogRestritoConfig',
    'pratique.apps.PratiqueConfig',
    'gerencia.apps.GerenciaConfig',
    'tasks.apps.TasksConfig',
    'saci.apps.SaciConfig',
    'week.apps.WeekConfig',
    'sisca.apps.SiscaConfig',
    'captcha',
    'impersonate',
    'corretor_ini',
    'fase0',
    'serpro',
    'inep',
    #'channels',
    #'websockets',
    #'editor',
    #'api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # obi
    'impersonate.middleware.ImpersonateMiddleware',
    'django.contrib.flatpages.middleware.FlatpageFallbackMiddleware',
]

ROOT_URLCONF = 'obi2026.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [Path(BASE_DIR) / 'principal' / 'templates' / 'principal',
                 Path(BASE_DIR) / 'principal' / 'templates' / 'flatpages',
                 Path(BASE_DIR) / 'blog' / 'templates' / 'blog',
                 Path(BASE_DIR) / 'blog_restrito' / 'templates' / 'blog_restrito',
                 Path(BASE_DIR) / 'fase2b' / 'templates' ,
                 Path(BASE_DIR) / 'gerencia' / 'templates' / 'gerencia'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'obi2026.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'obi2026',
        'USER': 'obi',
        'PASSWORD': 'guga.LC',
        'HOST': 'localhost',
        'PORT': '',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'pt-BR'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT =   Path(BASE_DIR) / "static_root"
STATICFILES_DIRS = [
  Path(BASE_DIR) / "static",
]

###############
# bootstrap messages
###############

MESSAGE_TAGS = {
        messages.DEBUG: 'alert-secondary',
        messages.INFO: 'alert-info',
        messages.SUCCESS: 'alert-success',
        messages.WARNING: 'alert-warning',
        messages.ERROR: 'alert-danger',
}

###############
# sites
###############
SITE_ID = 1

###############
# Date input formats
###############
DATE_INPUT_FORMATS = [
    '%d/%m/%Y', '%d-%m-%Y', # '%Y-%m-%d', # '25/10/2006', '25-10-2006', '2006-10-25'
]
DATE_FORMAT = "d/m/Y"
SHORT_DATE_FORMAT = "d/m/Y"

###############
# Files
###############
MEDIA_ROOT = Path(BASE_DIR) / 'media'
MEDIA_URL = '/media/'
DATA_UPLOAD_MAX_NUMBER_FIELDS = 2000

###############
# models
###############
DEFAULT_AUTO_FIELD='django.db.models.AutoField'

##############
# SMTP - EMAIL
##############
EMAIL = 'smtp'
if DEBUG:
    EMAIL = 'file'

DEFAULT_FROM_EMAIL = "Coordenação da OBI{} <olimpinf@ic.unicamp.br>".format(YEAR)
DEFAULT_REPLY_TO_EMAIL = "Coordenação da OBI{} <olimpinf@ic.unicamp.br>".format(YEAR)
EMAIL_TIMEOUT = 30 # for connection, in seconds

if EMAIL == 'file':
  # log to file instead of sending messages
  EMAIL_BACKEND = 'django.core.mail.backends.filebased.EmailBackend'
  EMAIL_FILE_PATH = '/tmp/django-messages' # change this to a proper location
elif EMAIL == 'console':
  # log to console instead of sending messages
  EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
elif EMAIL == 'dumb':
  # python -m smtpd -n -c DebuggingServer localhost:1025
  EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
  EMAIL_HOST_PORT = 1025
  EMAIL_HOST = 'localhost' # localhost is default
elif EMAIL == 'smtp':
  # send messages
  EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
  EMAIL_HOST = "smtp3.xmailer.com.br"
  EMAIL_HOST_PORT = 587
  EMAIL_HOST_USER = "olimpiada@olimpiada.ic.unicamp.br"
  EMAIL_HOST_PASSWORD = "dd7g0c0eyf"
  EMAIL_USE_TLS = False # TLS is not working for the new machine
elif EMAIL == 'smtp_unicamp':
  # send messages
  EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
  EMAIL_HOST = "taquaral.ic.unicamp.br"
  EMAIL_HOST_PORT = 587
  EMAIL_HOST_USER = "olimpinf"
  EMAIL_HOST_PASSWORD = "pric23weg"
  EMAIL_USE_TLS = True
else:
  # log to console instead of sending messages
  EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'


##############
# LOG IN AND LOGOUT
##############
LOGIN_URL = '/contas/login/'

##############
# LOGGING
##############
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format' : "[%(asctime)s] %(levelname)s [%(name)s:%(lineno)s] %(message)s",
            'datefmt' : "%d/%b/%Y %H:%M:%S"
        },
        'simple': {
            'format': '%(levelname)s %(message)s'
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        },
        'file_cadastro': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': Path(BASE_DIR) / 'CADASTRO.log',
            'formatter': 'verbose'
        },
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': Path(BASE_DIR) / 'OBI.log',
            'formatter': 'verbose'
        },
        'file_restrito': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': Path(BASE_DIR) / 'RESTRITO.log',
            'formatter': 'verbose'
        },
        'file_gerencia': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': Path(BASE_DIR) / 'GERENCIA.log',
            'formatter': 'verbose'
        },
        'file_exams': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': Path(BASE_DIR) / 'EXAMS.log',
            'formatter': 'verbose'
        },
        'file_fase1': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': Path(BASE_DIR) / 'FASE1.log',
            'formatter': 'verbose'
        },
        'file_cms': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': Path(BASE_DIR) / 'CMS.log',
            'formatter': 'verbose'
        },
        'file_lsp': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': Path(BASE_DIR) / 'LSP.log',
            'formatter': 'verbose'
        },
        'file_api': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': Path(BASE_DIR) / 'API.log',
            'formatter': 'verbose'
        },
    },
    'loggers': {
        'django': {
            'handlers':['file'],
            'propagate': True,
            'level':'INFO',
        },
        'obi': {
            'handlers': ['file'],
            'level': 'INFO',
        },
        'saci': {
            'handlers': ['file'],
            'level': 'INFO',
        },
        'cadastro': {
            'handlers': ['file_cadastro'],
            'level': 'INFO',
        },
        'restrito': {
            'handlers': ['file_restrito'],
            'level': 'INFO',
        },
        'gerencia': {
            'handlers': ['file_gerencia'],
            'level': 'INFO',
        },
        'exams': {
            'handlers': ['file_exams'],
            'level': 'INFO',
        },
        'fase1': {
            'handlers': ['file_fase1'],
            'level': 'INFO',
        },
        'cms': {
            'handlers': ['file_cms'],
            'level': 'INFO',
        },
        "lsp": {
            "handlers": ["file_lsp"],
            "level": "INFO",
            "propagate": True
        },
        "api": {
            "handlers": ["file_api"],
            "level": "INFO",
            "propagate": True
        },
    }
}


#### FILE UPLOAD
DATA_UPLOAD_MAX_MEMORY_SIZE = 104857600  # 100 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 104857600

    
###############
# cms
###############

CMS_HOST = {5: 'pj.provas.ic.unicamp.br', 3: 'p1.provas.ic.unicamp.br', 4: 'p2.provas.ic.unicamp.br', 6: 'ps.provas.ic.unicamp.br'}

###############
# pratique
###############

if DEBUG:
    SSH_HOSTNAME_PRATIQUE = '192.168.0.15'
    SSH_USERNAME_PRATIQUE = 'olimpinf'
else:
    SSH_HOSTNAME_PRATIQUE = '192.168.0.15'
    SSH_USERNAME_PRATIQUE = 'olimpinf'

###############
# exams
###############
UA_SECRET = os.environ.get("UA_SECRET", "1hrs5g1qs@svr-o(-3atjnz8evwmake03kyjwute023mdeu")

###############
# sisca
###############
# only to use builder
#SSH_SISCA_HOSTNAME='143.106.73.46'
SSH_SISCA_HOSTNAME='192.168.0.112'
SSH_SISCA_USERNAME='exec_corretor'
