from .models import (ExamFase1, TesteFase1, ExamFase1b,
                     SubTesteFase1, ResTesteFase1, SubTesteFase1Judge, ResTesteFase1Judge,
                     SubProvaFase1A, ResProvaFase1A, SubProvaFase1AJudge, ResProvaFase1AJudge,
                     SubProvaFase1B, ResProvaFase1B, SubProvaFase1BJudge, ResProvaFase1BJudge,
                     ExamFase2, SubProvaFase2, ResProvaFase2, SubProvaFase2Judge, ResProvaFase2Judge,
                     ExamFase2b,
                     ExamFase3, SubProvaFase3, ResProvaFase3, SubProvaFase3Judge, ResProvaFase3Judge,
                     ExamCfObi, SubProvaCfObi, ResProvaCfObi, SubProvaCfObiJudge, ResProvaCfObiJudge)

from principal.models import SubWWW, ResWWW
from datetime import datetime, timezone, timedelta

NOTICE_F1I = 'A cada dia, o ambiente de prova estará aberto das 8:00 às 23:00. Você deve iniciar a prova no máximo 22:00.'
NOTICE_F0P = 'A cada dia, o ambiente de prova estará aberto das 8:00 às 22:00.'
NOTICE_F1P = 'A cada dia, o ambiente de prova estará aberto das 8:00 às 23:00. Você deve iniciar a prova no máximo 21:00.'
NOTICE_CFOBI = 'Você deve iniciar a prova até no máximo 14:00. A participação na CF-OBI é opcional e não impacta o resultado final das competidoras na OBI. Veja mais informações sobre esta prova em <a href="https://olimpiada.ic.unicamp.br/competicao_feminina"><tt>https://olimpiada.ic.unicamp.br/competicao_feminina</tt></a>'
#NOTICE_F2I = 'O ambiente de prova estará aberto das 09:00 às 19:00. Você deve iniciar a prova no máximo 18:00.'
NOTICE_F2I =  '' #'Prova presencial, a ser feita na escola, sob supervisão de um professor, duração uma hora.'
NOTICE_F2PJ = '' # 'Prova presencial, a ser feita na escola, sob supervisão de um professor, duração duas horas.'
NOTICE_F2P2 = '' # 'Prova presencial, a ser feita na escola, sob supervisão de um professor, duração três horas.'
NOTICE_F2PJb = 'Esta prova "extra", opcional, está sendo oferecida porque vários alunos foram prejudicados pela lentidão no acesso à prova do dia 21/08. O ambiente de prova estará aberto das 07:00 às 19:00. Você deve iniciar a prova no máximo 17:00.'
NOTICE_F2P2b = 'Esta prova "extra", opcional, está sendo oferecida porque vários alunos foram prejudicados pela lentidão no acesso à prova do dia 21/08. O ambiente de prova estará aberto das 07:00 às 19:00. Você deve iniciar a prova no máximo 16:00.'
NOTICE_F3I =  'Início: 09:00' #'Você deve iniciar a prova no máximo 18:00.'
NOTICE_F3PJ = 'Início: 08:00' #'Você deve iniciar a prova no máximo 12:00.'
NOTICE_F3P2 = 'Início: 13:00' # 'Você deve iniciar a prova no máximo 10:00.'
NOTICE_F3PS = 'Início: 13:00' # 'Você deve iniciar a prova no máximo 10:00.'
TIMEZONE = 3
EXAMS = {
    'cfobif1': {
        'exam_title': 'Prova da Competição Feminina da OBI',
        'exam_descriptor': 'cfobif1',
        'exam_show_link': True,
        'exam_show_results': {'p': True},
        'exam_show_results_coord':  {'p': True},
        'exam_show_results_all':  {'p': False},
        'exam_show_classif': False,
        'exam_show_classif_coord': False,
        'exam_show_classif_all': False,
        'exam_duration': {'pj': 180, 'p1': 180, 'p2': 180},
        'exam_duration_notice': {'pj': NOTICE_CFOBI, 'p1': NOTICE_CFOBI, 'p2': NOTICE_CFOBI},
        'exam_submissions': {'pj': 50, 'p1': 50, 'p2': 50},
        'exam_object': ExamCfObi,
        'exam_db': 'corretor',
        'exam_table_submissions': SubProvaCfObi,
        'exam_table_results': ResProvaCfObi,
        'exam_table_submissions_judge': SubProvaCfObiJudge,
        'exam_table_results_judge': ResProvaCfObiJudge,
        'exam_date_start': {'p': datetime.fromisoformat('2023-09-01 08:00:00 -03:00')},
        'exam_date_finish': {'p': datetime.fromisoformat('2023-09-01 17:00:00 -03:00')},
        'exam_prog_url': {5: 'prova_pj,', 3: 'prova_p1', 4: 'prova_p2'},
        'exam_superusers': (12944,12945,12946),
        'exam_contest_id': 3,
    },
    'provaf3': {
        'exam_title': 'Prova da Fase 3 (Fase Nacional)',
        'exam_descriptor': 'provaf3',
        'exam_show_link': False,
        'exam_show_results': {'i': False, 'p': False},
        'exam_show_results_coord':  {'i': False, 'p': False},
        'exam_show_results_all':  {'i': False, 'p': False},
        'exam_show_classif': False,
        'exam_show_classif_coord': False,
        'exam_show_classif_all': False,
        'exam_duration': {'ij': 120, 'i1': 120, 'i2': 120, 'pj': 180, 'p1': 240, 'p2': 300, 'ps': 300},
        'exam_duration_notice': {'ij': NOTICE_F3I, 'i1': NOTICE_F3I, 'i2': NOTICE_F3I, 'pj': NOTICE_F3PJ, 'p1': NOTICE_F3PJ, 'p2': NOTICE_F3P2, 'ps': NOTICE_F3P2},
        'exam_submissions': {'ij': 50, 'i1': 50, 'i2': 50, 'pj': 100, 'p1': 100, 'p2': 100, 'ps': 100},
        'exam_object': ExamFase3,
        'exam_db': 'corretor',
        'exam_table_submissions': SubProvaFase1A,
        'exam_table_results': ResProvaFase1A,
        'exam_table_submissions_judge': SubProvaFase1AJudge,
        'exam_table_results_judge': ResProvaFase1AJudge,
        'exam_date_start': {'i': datetime.fromisoformat('2022-10-15 09:00:00 -03:00'), 'p': datetime.fromisoformat('2022-10-01 09:00:00 -03:00')},
        'exam_date_finish': {'i': datetime.fromisoformat('2022-10-15 11:00:00 -03:00'), 'p': datetime.fromisoformat('2022-10-01 18:00:00 -03:00')},
        'exam_prog_url': {5: 'prova_pj,', 3: 'prova_p1', 4: 'prova_p2', 6: 'prova_ps'},
        'exam_superusers': [],
        'exam_contest_id': 4,
    },
    'provaf2': {
        'exam_title': 'Prova da Fase 2 (Fase Estadual)',
        'exam_descriptor': 'provaf2',
        'exam_show_link': False,
        'exam_show_results': {'i': True, 'p': True},
        'exam_show_results_coord':  {'i': True, 'p': True},
        'exam_show_results_all':  {'i': False, 'p': False},
        'exam_show_classif': True,
        'exam_show_classif_coord': True,
        'exam_show_classif_all': True,
        'exam_duration': {'ij': 60, 'i1': 60, 'i2': 60, 'pj': 120, 'p1': 120, 'p2': 180, 'ps': 180},
        'exam_duration_notice': {'ij': NOTICE_F2I, 'i1': NOTICE_F2I, 'i2': NOTICE_F2I, 'pj': NOTICE_F2PJ, 'p1': NOTICE_F2PJ, 'p2': NOTICE_F2P2, 'ps': NOTICE_F2P2},
        'exam_submissions': {'ij': 50, 'i1': 50, 'i2': 50, 'pj': 50, 'p1': 50, 'p2': 50, 'ps': 50},
        'exam_object': ExamFase2,
        'exam_db': 'corretor',
        'exam_table_submissions': SubProvaFase1A,
        'exam_table_results': ResProvaFase1A,
        'exam_table_submissions_judge': SubProvaFase1AJudge,
        'exam_table_results_judge': ResProvaFase1AJudge,
        'exam_date_start': {'i': datetime.fromisoformat('2022-08-16 07:00:00 -03:00'), 'p': datetime.fromisoformat('2022-08-23 09:00:00 -03:00')},
        'exam_date_finish': {'i': datetime.fromisoformat('2022-08-16 18:00:00 -03:00'), 'p': datetime.fromisoformat('2022-08-23 17:00:00 -03:00')},
        'exam_prog_url': {5: 'prova_pj,', 3: 'prova_p1', 4: 'prova_p2', 6: 'prova_ps'},
        'exam_superusers': [],
        'exam_contest_id': 2,
    },
    'provaf1': {
        'exam_title': 'Prova da Fase 1 (Fase Local)',
        'exam_descriptor': 'provaf1',
        'exam_show_link': False,
        'exam_show_results': {'i': True, 'p': True},
        'exam_show_results_coord':  {'i': True, 'p': True},
        'exam_show_results_all':  {'i': True, 'p': True},
        'exam_show_classif': True,
        'exam_show_classif_coord': True,
        'exam_show_classif_all': True,
        'exam_duration': {'ij': 60, 'i1': 60, 'i2': 60, 'pj': 120, 'p1': 120, 'p2': 120, 'ps': 120},
        'exam_duration_notice': {'ij': NOTICE_F1I, 'i1': NOTICE_F1I, 'i2': NOTICE_F1I, 'pj': NOTICE_F1P, 'p1': NOTICE_F1P, 'p2': NOTICE_F1P, 'ps': NOTICE_F1P},
        'exam_submissions': {'ij': 50, 'i1': 50, 'i2': 50, 'pj': 50, 'p1': 50, 'p2': 50, 'ps': 50},
        'exam_object': ExamFase1,
        'exam_db': 'corretor',
        'exam_table_submissions': SubProvaFase1A,
        'exam_table_results': ResProvaFase1A,
        'exam_table_submissions_judge': SubProvaFase1AJudge,
        'exam_table_results_judge': ResProvaFase1AJudge,
        'exam_date_start': {'i': datetime.fromisoformat('2022-05-31 07:00:00 -03:00'), 'p': datetime.fromisoformat('2021-06-13 08:00:00 -03:00')},
        'exam_date_finish': {'i': datetime.fromisoformat('2022-06-02 23:00:00 -03:00'), 'p': datetime.fromisoformat('2021-06-15 23:00:00 -03:00')},
        'exam_prog_url': {5: 'prova_pj,', 3: 'prova_p1', 4: 'prova_p2', 6: 'prova_ps'},
        'exam_superusers': [],
        'exam_contest_id': 1,
    },
    'testef1': {
        'exam_title': 'Prova Teste',
        'exam_descriptor': 'testef1',
        'exam_show_link': False,
        'exam_show_results': {'i': False, 'p': True},
        'exam_show_results_coord': {'i':False, 'p': True},
        'exam_show_results_all': {'i': False, 'p': False},
        'exam_show_classif': False,
        'exam_show_classif_coord': False,
        'exam_show_classif_all': False,
        'exam_duration': {'ij': 20, 'i1': 20, 'i2': 20, 'pj': 30, 'p1': 30, 'p2': 30, 'ps': 30},
        'exam_duration_notice': {'ij': '', 'i1': '', 'i2': '', 'pj': NOTICE_F0P, 'p1': NOTICE_F0P, 'p2': NOTICE_F0P, 'ps': NOTICE_F0P},
        'exam_submissions': {'ij': 50, 'i1': 50, 'i2': 50, 'pj': 50, 'p1': 50, 'p2': 50, 'ps': 50},
        'exam_object': TesteFase1,
        'exam_db': 'corretor',
        'exam_table_submissions': SubTesteFase1,
        'exam_table_results': ResTesteFase1,
        'exam_table_submissions_judge': SubTesteFase1Judge,
        'exam_table_results_judge': ResTesteFase1Judge,
        'exam_date_start': {'i': datetime.fromisoformat('2021-05-15 07:00:00 -03:00'), 'p': datetime.fromisoformat('2022-06-04 07:00:00 -03:00')},
        'exam_date_finish': {'i': datetime.fromisoformat('2021-10-01 23:59:59 -03:00'), 'p': datetime.fromisoformat('2022-06-11 23:00:00 -03:00')},
        #'exam_date_start':  {'i': datetime(2021,5,5,7,0,0,0,timezone(-timedelta(hours=TIMEZONE))), 'p': datetime(2021,5,5,7,0,0,0,timezone(-timedelta(hours=TIMEZONE)))},
        #'exam_date_finish': {'i':datetime(2021,6,20,23,59,59,23,timezone(-timedelta(hours=TIMEZONE))), 'p': datetime(2021,6,12,23,59,59,59,timezone(-timedelta(hours=TIMEZONE)))},
        'exam_prog_url': {'pj': 'prova_pj', 'p1': 'prova_p1', 'p2': 'prova_p2/', 'ps': 'prova_ps'},
        'exam_superusers': [],
        'exam_contest_id': 0,
    }
}
