from .models import (ExamFase1, TesteFase1, ExamFase1b,
                     SubTesteFase1, ResTesteFase1, SubTesteFase1Judge, ResTesteFase1Judge,
                     SubProvaFase1A, ResProvaFase1A, SubProvaFase1AJudge, ResProvaFase1AJudge,
                     SubProvaFase1B, ResProvaFase1B, SubProvaFase1BJudge, ResProvaFase1BJudge,
                     ExamFase2, SubProvaFase2, ResProvaFase2, SubProvaFase2Judge, ResProvaFase2Judge,
                     ExamFase2b,
                     ExamFase3, SubProvaFase3, ResProvaFase3, SubProvaFase3Judge, ResProvaFase3Judge,
                     ExamCfObi, SubProvaCfObi, ResProvaCfObi, SubProvaCfObiJudge, ResProvaCfObiJudge)

from principal.models import SubWWW, ResWWW
from datetime import datetime, timezone, timedelta

NOTICE_F1I = ''
NOTICE_F0P = 'A cada dia, o ambiente de prova estará aberto das 8:00 às 21:00, exceto nos dia 7 e 8 de junho, sábado e domingo, quando o ambiente de prova estará aberto das 8:00 às 18:00. Você deve iniciar a prova no máximo meia hora antes do fechamento do ambiente de prova.'
NOTICE_F1P = 'A cada dia, o ambiente de prova estará aberto das 8:00 às 21:00. Você deve iniciar a prova no máximo duas horas antes do fechamento do ambiente de prova.'
NOTICE_CFOBI = 'Você deve iniciar a prova até no máximo 15:00. A participação na CF-OBI é opcional e não impacta o resultado final das competidoras na OBI. Veja mais informações sobre esta prova em <a href="https://olimpiada.ic.unicamp.br/info/competicao_feminina"><tt>https://olimpiada.ic.unicamp.br/info/competicao_feminina</tt></a>'
#NOTICE_F2I = 'O ambiente de prova estará aberto das 09:00 às 19:00. Você deve iniciar a prova no máximo 18:00.'
NOTICE_F2I =  'Realizada presencialmente, na escola, sob supervisão de um professor, duração uma hora.'
NOTICE_F2PJ = 'Realizada presencialmente, na escola, sob supervisão de um professor, duração duas horas. Para o nível Júnior o Ambiente de Prova estará aberto de 08:00 até 18:00 (horário de Brasília). O competidor do nível Júnior deve iniciar a prova no máximo 16:00.'
NOTICE_F2P2 = 'Realizada presencialmente, na escola, sob supervisão de um professor, duração três horas. O Ambiente de Prova estará aberto de 08:00 até 21:00 (horário de Brasília, estendido a pedido das escolas). O competidor deve iniciar a prova no máximo 18:00.'
NOTICE_F2PJb = ''
NOTICE_F2P2b = 'Esta prova "extra", opcional, está sendo oferecida porque vários alunos da modalidade Programação Nível 2 foram prejudicados pela lentidão no acesso à prova do dia 16/08. A duração da prova é 3 horas. O ambiente de prova estará aberto das 08:00 às 21:00. Você deve iniciar a prova no máximo 18:00.'
NOTICE_F3I =  'Início: 10:00' #'Você deve iniciar a prova no máximo 18:00.'
NOTICE_F3PJ = 'Início: 08:00' #'Você deve iniciar a prova no máximo 12:00.'
NOTICE_F3P1 = 'Início: 08:00' #'Você deve iniciar a prova no máximo 12:00.'
NOTICE_F3P2 = 'Início: 13:00' # 'Você deve iniciar a prova no máximo 10:00.'
NOTICE_F3PS = 'Início: 13:00' # 'Você deve iniciar a prova no máximo 10:00.'

TIMEZONE = 3

EXAMS = {
    'provaf1': {
        'exam_title': 'Prova da Fase 1 (Fase Local)',
        'exam_contest_id': 1,
        'exam_descriptor': 'provaf1',
        'exam_show_link': False,
        'exam_show_results': {'i': True, 'p': True},
        'exam_show_results_coord':  {'i': True, 'p': True},
        'exam_show_results_all':  {'i': False, 'p': False},
        'exam_show_classif': True,
        'exam_show_classif_coord': True,
        'exam_show_classif_all': False,
        'exam_duration': {'ij': 60, 'i1': 60, 'i2': 60, 'pj': 120, 'p1': 120, 'p2': 120, 'ps': 120},
        'exam_duration_notice': {'ij': NOTICE_F1I, 'i1': NOTICE_F1I, 'i2': NOTICE_F1I, 'pj': NOTICE_F1P, 'p1': NOTICE_F1P, 'p2': NOTICE_F1P, 'ps': NOTICE_F1P},
        'exam_submissions': {'ij': 50, 'i1': 50, 'i2': 50, 'pj': 50, 'p1': 50, 'p2': 50, 'ps': 50},
        'exam_object': ExamFase1,
        'exam_db': 'corretor',
        'exam_table_submissions': SubProvaFase1A,
        'exam_table_results': ResProvaFase1A,
        'exam_table_submissions_judge': SubProvaFase1AJudge,
        'exam_table_results_judge': ResProvaFase1AJudge,
        'exam_date_start': {'i': datetime.fromisoformat('2025-06-05 07:00:00 -03:00'), 'p': datetime.fromisoformat('2025-06-12 08:00:00 -03:00')},
        'exam_date_finish': {'i': datetime.fromisoformat('2025-06-07 18:00:00 -03:00'), 'p': datetime.fromisoformat('2025-06-14 21:00:00 -03:00')},
        'exam_prog_url': {5: 'prova_pj,', 3: 'prova_p1', 4: 'prova_p2', 6: 'prova_ps'},
        'exam_superusers': [],
    },
    'cfobif1': {
        'exam_title': 'Prova da Competição Feminina da OBI',
        'exam_contest_id': 3,
        'exam_descriptor': 'cfobif1',
        'exam_show_link': False,
        'exam_show_results': {'i': False, 'p': True},
        'exam_show_results_coord':  {'i': False, 'p': True},
        'exam_show_results_all':  {'i': False, 'p': False},
        'exam_show_classif': False,
        'exam_show_classif_coord': False,
        'exam_show_classif_all': False,
        'exam_duration': {'pj': 180, 'p1': 180, 'p2': 180},
        'exam_duration_notice': {'pj': NOTICE_CFOBI, 'p1': NOTICE_CFOBI, 'p2': NOTICE_CFOBI},
        'exam_submissions': {'pj': 50, 'p1': 50, 'p2': 50},
        'exam_object': ExamCfObi,
        'exam_db': 'corretor',
        'exam_table_submissions': SubProvaCfObi,
        'exam_table_results': ResProvaCfObi,
        'exam_table_submissions_judge': SubProvaCfObiJudge,
        'exam_table_results_judge': ResProvaCfObiJudge,
        'exam_date_start': {'p': datetime.fromisoformat('2025-09-12 08:00:00 -03:00')},
        'exam_date_finish': {'p': datetime.fromisoformat('2025-09-12 18:00:00 -03:00')},
        'exam_prog_url': {5: 'prova_pj,', 3: 'prova_p1', 4: 'prova_p2'},
        'exam_superusers': (),
    },
    'provaf3': {
        'exam_title': 'Prova da Fase 3 (Fase Nacional)',
        'exam_contest_id': 4,
        'exam_descriptor': 'provaf3',
        'exam_show_link': False,
        'exam_show_results': {'i': True, 'p': True},
        'exam_show_results_coord':  {'i': True, 'p': True},
        'exam_show_results_all':  {'i': False, 'p': False},
        'exam_show_classif': False,
        'exam_show_classif_coord': False,
        'exam_show_classif_all': False,
        'exam_duration': {'ij': 120, 'i1': 120, 'i2': 120, 'pj': 180, 'p1': 240, 'p2': 300, 'ps': 300},
        'exam_duration_notice': {'ij': NOTICE_F3I, 'i1': NOTICE_F3I, 'i2': NOTICE_F3I, 'pj': NOTICE_F3PJ, 'p1': NOTICE_F3P1, 'p2': NOTICE_F3P2, 'ps': NOTICE_F3P2},
        'exam_submissions': {'ij': 50, 'i1': 50, 'i2': 50, 'pj': 100, 'p1': 100, 'p2': 100, 'ps': 100},
        'exam_object': ExamFase3,
        'exam_db': 'corretor',
        'exam_table_submissions': SubProvaFase1A,
        'exam_table_results': ResProvaFase1A,
        'exam_table_submissions_judge': SubProvaFase1AJudge,
        'exam_table_results_judge': ResProvaFase1AJudge,
        'exam_date_start': {'i': datetime.fromisoformat('2025-09-20 10:00:00 -03:00'), 'p': datetime.fromisoformat('2025-09-27 08:00:00 -03:00')},
        'exam_date_finish': {'i': datetime.fromisoformat('2025-09-20 12:00:00 -03:00'), 'p': datetime.fromisoformat('2025-09-27 18:00:00 -03:00')},
        'exam_prog_url': {5: 'prova_pj,', 3: 'prova_p1', 4: 'prova_p2', 6: 'prova_ps'},
        'exam_superusers': [],
    },
    'provaf2': {
        'exam_title': 'Prova da Fase 2 (Fase Estadual)',
        'exam_contest_id': 2,
        'exam_descriptor': 'provaf2',
        'exam_show_link': False,
        'exam_show_results': {'i': True, 'p': True},
        'exam_show_results_coord':  {'i': True, 'p': True},
        'exam_show_results_all':  {'i': False, 'p': False},
        'exam_show_classif': True,
        'exam_show_classif_coord': True,
        'exam_show_classif_all': False,
        'exam_duration': {'ij': 60, 'i1': 60, 'i2': 60, 'pj': 120, 'p1': 180, 'p2': 180, 'ps': 180},
        'exam_duration_notice': {'ij': NOTICE_F2I, 'i1': NOTICE_F2I, 'i2': NOTICE_F2I, 'pj': NOTICE_F2PJ, 'p1': NOTICE_F2P2, 'p2': NOTICE_F2P2, 'ps': NOTICE_F2P2},
        'exam_submissions': {'ij': 50, 'i1': 50, 'i2': 50, 'pj': 50, 'p1': 50, 'p2': 50, 'ps': 50},
        'exam_object': ExamFase2,
        'exam_db': 'corretor',
        'exam_table_submissions': SubProvaFase1A,
        'exam_table_results': ResProvaFase1A,
        'exam_table_submissions_judge': SubProvaFase1AJudge,
        'exam_table_results_judge': ResProvaFase1AJudge,
        'exam_date_start': {'i': datetime.fromisoformat('2025-08-09 07:00:00 -03:00'), 'p': datetime.fromisoformat('2025-08-16 08:00:00 -03:00')},
        'exam_date_finish': {'i': datetime.fromisoformat('2025-08-09 18:00:00 -03:00'), 'p': datetime.fromisoformat('2025-08-16 21:00:00 -03:00')},
        'exam_prog_url': {5: 'prova_pj,', 3: 'prova_p1', 4: 'prova_p2', 6: 'prova_ps'},
        'exam_superusers': [],
    },
    'provaf2b': {
        'exam_title': 'Prova da Fase 2 (Fase Estadual) Turno B',
        'exam_descriptor': 'provaf2b',
        'exam_show_link': False,
        'exam_show_results': {'i': False, 'p': False},
        'exam_show_results_coord':  {'i': False, 'p': False},
        'exam_show_results_all':  {'i': False, 'p': False},
        'exam_show_classif': False,
        'exam_show_classif_coord': False,
        'exam_show_classif_all': False,
        'exam_duration': {'ij': 60, 'i1': 60, 'i2': 60, 'pj': 120, 'p1': 120, 'p2': 180, 'ps': 180},
        'exam_duration_notice': {'ij': NOTICE_F2I, 'i1': NOTICE_F2I, 'i2': NOTICE_F2I, 'pj': NOTICE_F2PJ, 'p1': NOTICE_F2PJ, 'p2': NOTICE_F2P2, 'ps': NOTICE_F2P2},
        'exam_submissions': {'ij': 50, 'i1': 50, 'i2': 50, 'pj': 50, 'p1': 50, 'p2': 50, 'ps': 50},
        'exam_object': ExamFase2b,
        'exam_db': 'corretor',
        'exam_table_submissions': SubProvaFase1A,
        'exam_table_results': ResProvaFase1A,
        'exam_table_submissions_judge': SubProvaFase1AJudge,
        'exam_table_results_judge': ResProvaFase1AJudge,
        'exam_date_start': {'i': datetime.fromisoformat('2025-08-09 07:00:00 -03:00'), 'p': datetime.fromisoformat('2025-08-26 08:00:00 -03:00')},
        'exam_date_finish': {'i': datetime.fromisoformat('2025-08-09 18:00:00 -03:00'), 'p': datetime.fromisoformat('2025-08-26 21:00:00 -03:00')},
        'exam_prog_url': {5: 'prova_pj,', 3: 'prova_p1', 4: 'prova_p2', 6: 'prova_ps'},
        'exam_superusers': [],
        'exam_contest_id': 3,
    },
    'testef1': {
        'exam_title': 'Prova Teste',
        'exam_descriptor': 'testef1',
        'exam_show_link': False,
        'exam_show_results': {'i': False, 'p': False},
        'exam_show_results_coord': {'i':False, 'p': False},
        'exam_show_results_all': {'i': False, 'p': False},
        'exam_show_classif': False,
        'exam_show_classif_coord': False,
        'exam_show_classif_all': False,
        'exam_duration': {'ij': 20, 'i1': 20, 'i2': 20, 'pj': 30, 'p1': 30, 'p2': 30, 'ps': 30},
        'exam_duration_notice': {'ij': '', 'i1': '', 'i2': '', 'pj': NOTICE_F0P, 'p1': NOTICE_F0P, 'p2': NOTICE_F0P, 'ps': NOTICE_F0P},
        'exam_submissions': {'ij': 50, 'i1': 50, 'i2': 50, 'pj': 50, 'p1': 50, 'p2': 50, 'ps': 50},
        'exam_object': TesteFase1,
        # 'exam_db': 'corretor',
        # 'exam_table_submissions': SubTesteFase1,
        # 'exam_table_results': ResTesteFase1,
        # 'exam_table_submissions_judge': SubTesteFase1Judge,
        # 'exam_table_results_judge': ResTesteFase1Judge,
        'exam_date_start': {'i': datetime.fromisoformat('2025-05-05 07:00:00 -03:00'), 'p': datetime.fromisoformat('2025-06-05 08:00:00 -03:00')},
        'exam_date_finish': {'i': datetime.fromisoformat('2025-05-21 23:59:59 -03:00'), 'p': datetime.fromisoformat('2025-06-09 21:00:00 -03:00')},
        #'exam_date_start':  {'i': datetime(2021,5,5,7,0,0,0,timezone(-timedelta(hours=TIMEZONE))), 'p': datetime(2021,5,5,7,0,0,0,timezone(-timedelta(hours=TIMEZONE)))},
        #'exam_date_finish': {'i':datetime(2021,6,20,23,59,59,23,timezone(-timedelta(hours=TIMEZONE))), 'p': datetime(2021,6,12,23,59,59,59,timezone(-timedelta(hours=TIMEZONE)))},
        'exam_prog_url': {'pj': 'prova_pj', 'p1': 'prova_p1', 'p2': 'prova_p2', 'ps': 'prova_ps'},
        'exam_superusers': [],
        'exam_contest_id': 1,
    }
}

DEFAULT_CONTEST_ID = EXAMS['provaf1']['exam_contest_id']
DEFAULT_CONTEST_ID_CFOBI = EXAMS['cfobif1']['exam_contest_id']
